#!/bin/bash
### GITHUB PART ###
#git clone https://github.com/larkinrd/AFIT-CSCE689-HW4-S.git

### NECESSARY Packages/Libraries ####
#sudo apt-get install libcrypto++-doc
#sudo apt-get install libcrypto++-dev
#sudo apt-get install libcrypto++-utils

### CONFIGURE Lt Col Noels Code ###
#cd AFIT-CSCE689-HW4-S
#autoreconf -i
#./configure
#make

### CREATE a sharedkey ####
#./src/keygen sharedkey.bin

### KILL ports used in previous attempts
fuser -k 9999/tcp
fuser -k 9998/tcp
fuser -k 9997/tcp

### Delete old log files
rm ds*

###LAUNCH Terminals###
# Get Port Numbers for each replication server
#echo -e "Enter 3 port no."
#read port1 port2 port3
#for (( i=1;i<4;i++)); do
#xfce4-terminal --title=SVR1DRN1 -e "./src/repsvr -p $port$i -t 10 -o svr$i.txt -v 3 ./data/SingleDroneN$1.bin"
#sleep 5s
### add a -H to keep terminal open
xfce4-terminal --title=DS19999DRN1 -e "./src/repsvr -p 9999 -t 3 -o ds19999.txt -v 0 ./data/SingleDroneN1.bin"
xfce4-terminal --title=DS29998DRN2 -e "./src/repsvr -p 9998 -t 3 -o ds19998.txt -v 0 ./data/SingleDroneN3.bin"
#xfce4-terminal --title=DS39997DRN3 -e "./src/repsvr -p 9997 -t 3 -o ds19997.txt -v 3 ./data/SingleDroneN2.bin"
#done
